version: "3"

services:
  # node-torrent:
  #   image: maxrsb/node-torrent
  #   container_name: node-torrent
  #   ports:
  #     - 3333:3333
  #     - 51413:51413
  #     - 51413:51413/udp
  #   environment:
  #     - PASSWORD=password #optional (default is admin)
  #     - USER_NAME=user #optional (default is pwd123)
  #     - DOWNLOAD_DIR=/downloads
  #   restart: unless-stopped
  #   volumes:
  #     # /downloads dir can be set to different dirname in the DOWNLOAD_DIR env variable
  #     - /media-server/tv:/downloads/series
  #     - /media-server/movies:/downloads/movies

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /plex/config:/config
      - /plex/tv:/tv
      - /plex/movies:/movies
    restart: unless-stopped
