version: "3"

services:
  postgres:
    image: postgres
    container_name: nextcloud_postgres
    restart: unless-stopped
    env_file:
      - postgres.env

  redis:
    container_name: nextcloud_redis
    image: redis:alpine
    restart: unless-stopped

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    env_file:
      - nextcloud.env
    volumes:
      - :/var/www/html
    depends_on:
      - postgres
      - redis
    ports:
      - 8081:80
