version: "3"

services:
  postgres:
    image: postgres:alpine
    container_name: nextcloud_postgres
    restart: unless-stopped
    volumes:
      - /nextcloud/postgres:/var/lib/postgresql/data
    env_file:
      - postgres.env

  redis:
    container_name: nextcloud_redis
    image: redis:alpine
    volumes:
      - /nextcloud/redis:/data
    restart: unless-stopped

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    env_file:
      - nextcloud.env
    volumes:
      - /nextcloud/data:/var/www/html
    depends_on:
      - postgres
      - redis
    ports:
      - 8081:80
